import legendary from './achievementsImg/Legendary.svg'
import epicOne from './achievementsImg/Epic.svg'
import epicTwo from './achievementsImg/EpicTwo.svg'
import rare from './achievementsImg/rare.svg'
import uncommon from './achievementsImg/uncommon.svg'

export const achievementsData = [
    {
        id: 1,
        icon: legendary,
        title: "1000 stars on my project",
        description: "I have contributed to Gutenberg, moment.js and react repositories in github.",
        status: "achieved",
        rarity: "legendary",
        date:'2024/10/09',
        condition: (stats) => stats.stars >= 1000,
    },
    {
        id: 2,
        icon:epicOne, 
        title: "Released personal website",
        description: "the site you are looking at right now -- yes, I did it! And it took me a few months.",
        status: "todo",
        rarity: "epic",
        date:'ongoing',
        condition: (stats) => stats.websiteReleased,
    },
    {
        id: 3,
        icon: epicTwo,
        title: "Developed open source plugin",
        description: "I have created a JS library for managing absolute positioned elements",
        status: "todo",
        rarity: "epic",
        date:'ongoing',
        condition: (stats) => stats.plugins >= 1,
    },
    {
        id: 4,
        icon: epicTwo ,
        title: "Gain 50 stars on a repository",
        description: "My most popular extension is gaining traction, I am aiming for at least 50 stars",
        status: "todo",
        rarity: "rare",
        date:'ongoing',
        condition: (stats) => stats.stars >= 50,
    },
    {
        id: 5,
        icon: rare,
        title: "Achieve 100 WPM writing speed",
        description: "My most popular extension is gaining traction, I am aiming for at least 50 stars",
        status: "todo",
        rarity: "uncommon",
        date: "ongoing",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 6,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 7,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 8,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 9,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 10,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id:11,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 12,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 13,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 14,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 15,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 16,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 17,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 18,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 19,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
    {
        id: 20,
        icon: epicOne ,
        title: "Achieve 100 WPM writing speed",
        description: "Fast typing legend.",
        status: "todo",
        rarity: "uncommon",
        condition: (stats) => stats.wpm >= 100,
    },
];
